### ISSUE TITLE
Backup fails but restic-robot shows success

### ISSUE THREAD

**Issue by varac** [Southclaws/restic-robot#8]
I wanted to start a new backup but restic-robot finished after 2s backup time with "backup completed" even there was nothing transfered (server directory is conpletely empty).
There's also no sign of any error in the logs

```
❯ docker-compose up    
Creating network "restic-robot_default" with the default driver
Pulling backup (southclaws/restic-robot:)...
latest: Pulling from southclaws/restic-robot
df20fa9351a1: Already exists
3c34c8da4207: Pull complete
5d88dfe983d2: Pull complete
5de6afcc5460: Pull complete
Digest: sha256:f763655497cf4916ceb880c04d7dfc560a2338745006a78ff5bec18f4b40f602
Status: Downloaded newer image for southclaws/restic-robot:latest
Creating restic-robot ... done
Attaching to restic-robot
restic-robot | {"level":"info","ts":"2020-10-07T18:54:41.991Z","caller":"restic-robot/main.go:207","msg":"ensuring backup repository exists"}
restic-robot | {"level":"info","ts":"2020-10-07T18:54:44.219Z","caller":"restic-robot/main.go:219","msg":"successfully created repository"}
restic-robot | {"level":"info","ts":"2020-10-07T18:54:44.219Z","caller":"restic-robot/main.go:85","msg":"backup started"}
restic-robot | {"level":"info","ts":"2020-10-07T18:54:46.519Z","caller":"restic-robot/main.go:136","msg":"backup completed","duration":2.299721993,"filesNew":5861,"filesChanged":0,"filesUnmodified":0,"filesProcessed":5861,"bytesAdded":34141634560,"bytesProcessed":31629246464}
```

I was using this docker-compose file:

```
---
# https://github.com/Southclaws/restic-robot#docker-compose
version: "3"

services:
  backup:
    container_name: 'restic-robot'
    image: southclaws/restic-robot
    # restart: always
    environment:
      # every day at 2am
      SCHEDULE: 0 0 2 * * *
      RESTIC_REPOSITORY: test
      RESTIC_PASSWORD: ...
      RUN_ON_BOOT: "true"
      # restic-robot runs `restic backup ${RESTIC_ARGS}`
      # so this is where you specify the directory and any other args.
      RESTIC_ARGS: /data
    volumes:
      # Bind whatever directories to the backup container.
      # You can safely bind the same directory to multiple containers.
      - "/etc:/data/etc"

```
